targets:
  $default:
    builders:
      # only to resolve build_runner conflicts
      dart_mappable_builder:
        options:
          build_extensions:
            'lib/{{path}}/{{file}}.dart':
              - 'lib/{{path}}/gen/{{file}}.mapper.dart'
              - 'lib/{{path}}/gen/{{file}}.init.dart'