name: app_links_deep_link_client
description: A App Links implementation of DeepLinkClient
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  app_links: ^6.4.0
  deep_link_client:
    path: ../deep_link_client
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
