name: getx_feature_hooks

environment:
  sdk: ^3.4.0

dependencies:
  mason: ^0.1.0-dev.52
  yaml: ^3.1.2
  dart_file_editor:
    git:
      url: https://github.com/egortabula/dart_file_editor.git
  


  
